name: Patch

on: [push]

jobs:
  patch:
    runs-on: windows-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
      - name: Patch
        run: nim c --run patch/patch.nim
      - name: Zip
        run: Compress-Archive -Path Sophia -DestinationPath Sophia.zip
      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Sophia.zip
          tag: rolling
          overwrite: true
          asset_content_type: application/zip